# helpers/constants.py
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATETIMETZ_FORMAT = "%Y-%m-%dT%H:%M:%Sz"
DATETIMETZ_WITH_MICROSECONDS_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"

CONCURRENT_REQUESTS_LIMIT = 10
DEFAULT_CLICKHOUSE_QUERY_LIMIT = 1_000_000
